[profile.default]
src = 'src'
solc = "0.7.6"
out = 'out'
libs = ['lib']
[fuzz]
runs = 1000
gas_reports = ["StakingRewards", "StakingRewardsFactory"]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
mumbai = "${POLYGON_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
polygon-mumbai = { key = "${POLYGON_API_KEY}" , url= "https://mumbai.polygonscan.com/"}
